# openssl gerrsa -out akshay.key 2048
# openssl req -new -key akshay.key -subj "CN=akshay" -out akshay.csr
# cat akshay.csr | base64


apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXVNdXRpdHVUM2VZZlhLeHk3NGdidmNGYXNOWm9PaTUzWUdjTXRxSHl2TWNBClZyN21Pcm1LNlB4cmlFay9NZHJma29QVzk0ZXo0bmFzOUVGKytNbEVsbHovemNSSWZ6eHRUQ2ZHSXRmWkVaMVIKUzJ1dEhteGFJRjRrNGIwT2V4NW81MVdDN2xwck4vZTB6Q3orSUxIVlk2SkhTL2Vza1h0Q0pNYnlWWnA4aEpTQgo2dkI1M0RvRk84OWpEQzU3YVFFTVBHTVB2T2J5RUkrTmtSaWtldWl0NmdPUjU3Q3BuZUxuejN3M2o4aFN0V25KCjUwekovMkhqWUNMZkVMY1U0cWdxc3E3WlZrYjQ5QW5MVFZSU3FPYXZFZ2lDbmxqbHhpdTIvMnFlb0hKRWF0REEKRnhSOXFzQ0t6RFN5eCtCQVhVdUVzQzNIQXN4ZkZLRXRUbEsxUXVyVTZRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQnlLdkc1ZHVTUHJqY1pKNkpJZU1lcmtFSG9SM2hnNHE0dDhSWmRiMXdSWWhEcjNrOXpuCkpBUnVIanc0YkdrRXZmWDRzeWZvRCt0QkJia2xDRW5xcXk4bFc3UHgzd3FxSkZ0QTV4bGliamFtRFNMKzJZNTcKQjJPRkFvdVlUVFE0M0RtUk5wRks5bmY2dzFlc1dPaElrWHBrb3haSTB0TWFsdE1kbTdaYjVlVXJnejBGb2I4SgpZa0NZUWdoZE9vMGNYL1ZXbHU2TGh0VDhrK2l3bHdHR080U0VUaGw0R0V0cTlvRWxJTTVhZGRFYXpoR1NQSVN1CjM4UVdBWUJYMEtvdnU0L2RYaVBxYzNEdWhkODQ5OGQ0cmZNckVnb0w2RWdaeFo2dmFwY0FwSE5TeGJJdW9OS2EKbzRWcnpWV1FyK3NIV3ZYVG1YaHlIVm1KNk8yb3JzcHFXMm89Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
