# kubectl create configmap webapp-config-map --from-literal=APP_COLOR=darkblue

apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
spec:
  containers:
    - name: webapp-color
      image: kodekloud/webapp-color
      envFrom:
        - configMapRef:
            name: webapp-config-map
